version: '3.9'

# services
services:
  # app service
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    image: blogsite-image
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./blogsite:/app

    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
